[package]
name = "LinearRegressionPractice"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
num-complex = "0.4.6"
plotly = "0.10.0"
rand = "0.8.5"
rustfft = "6.2.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
